//public async Task<GenerateMarketAnalysisResponse> GenerateAnalysisAsync(
//    MLApiRequestDto request,
//    CancellationToken cancellationToken = default)
//{
//    try
//    {
//        var requestUrl = $"{_mlApiBaseUrl}/api/v1/report";

//        _logger.LogInformation("========================================");
//        _logger.LogInformation("Calling ML API: {Url}", requestUrl);

//        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, requestUrl);

//        if (!string.IsNullOrWhiteSpace(_mlApiKey))
//            httpRequest.Headers.Add("X-API-Key", _mlApiKey);

//        // ✅ Build JSON request (NOT form-data!)
//        var jsonRequest = new
//        {
//            therapeutic_area = request.TherapeuticArea,
//            specific_product = request.SpecificProduct,
//            indication = request.Indication,
//            target_geography = string.Join(",", request.TargetGeography),
//            research_depth = string.Join(",", request.ResearchDepth),
//            files = request.Files.Select(f => new
//            {
//                file_id = f.FileId,
//                file_name = f.FileName,
//                file_url = f.FileUrl,
//                file_size = f.FileSize,
//                file_extension = f.FileExtension
//            }).ToList()
//        };

//        var jsonContent = JsonConvert.SerializeObject(jsonRequest, Formatting.Indented);

//        _logger.LogInformation("========================================");
//        _logger.LogInformation("Request JSON:");
//        _logger.LogInformation(jsonContent);
//        _logger.LogInformation("========================================");

//        httpRequest.Content = new StringContent(
//            jsonContent,
//            System.Text.Encoding.UTF8,
//            "application/json");

//        var response = await _httpClient.SendAsync(httpRequest, cancellationToken);
//        var responseContent = await response.Content.ReadAsStringAsync(cancellationToken);

//        _logger.LogInformation("ML API Status: {Status}", response.StatusCode);
//        _logger.LogInformation("Response Length: {Length} characters", responseContent.Length);

//        if (!response.IsSuccessStatusCode)
//        {
//            _logger.LogError("ML API Error: {Response}", responseContent);
//            throw new Exception($"ML API Error ({response.StatusCode}): {responseContent}");
//        }

//        _logger.LogInformation("Deserializing response...");

//        var result = JsonConvert.DeserializeObject<GenerateMarketAnalysisResponse>(responseContent);

//        if (result == null)
//            throw new JsonException("Received null when deserializing ML API response.");

//        _logger.LogInformation("✓ Analysis ID: {Id}", result.Id);
//        _logger.LogInformation("✓ Confidence: {Score}", result.ConfidenceScore);
//        _logger.LogInformation("✓ Generated By: {Count} sources", result.GeneratedBy.Count);
//        _logger.LogInformation("========================================");

//        return result;
//    }
//    catch (Exception ex)
//    {
//        _logger.LogError(ex, "ML API call failed");
//        throw;
//    }
//}



#region old
//#region MLApiService
//using ApplicationLayer.Contracts.DTOs;
//using ApplicationLayer.Interfaces.Services;
//using Microsoft.Extensions.Configuration;
//using Microsoft.Extensions.Logging;
//using Newtonsoft.Json;

//namespace InfrastructureLayer.Services;

//public class MLApiService : IMLApiService
//{
//    private readonly HttpClient _httpClient;
//    private readonly ILogger<MLApiService> _logger;
//    private readonly string _mlApiBaseUrl;
//    private readonly string? _mlApiKey;

//    public MLApiService(
//        HttpClient httpClient,
//        IConfiguration configuration,
//        ILogger<MLApiService> logger)
//    {
//        _httpClient = httpClient;
//        _logger = logger;

//        _mlApiBaseUrl = configuration["MLApi:BaseUrl"]
//            ?? throw new InvalidOperationException("MLApi:BaseUrl not configured");

//        _mlApiKey = configuration["MLApi:ApiKey"];

//        if (int.TryParse(configuration["MLApi:TimeoutSeconds"], out int timeout))
//            _httpClient.Timeout = TimeSpan.FromSeconds(timeout);
//    }



//    public async Task<GenerateMarketAnalysisResponse> GenerateAnalysisAsync(
//    MLApiRequestDto request,
//    CancellationToken cancellationToken = default)
//    {
//        try
//        {
//            var requestUrl = $"{_mlApiBaseUrl}/api/v1/report";

//            _logger.LogInformation("========================================");
//            _logger.LogInformation("DEBUG: TherapeuticArea = '{Value}'", request.TherapeuticArea ?? "NULL");
//            _logger.LogInformation("DEBUG: TargetGeography count = {Count}", request.TargetGeography?.Count ?? 0);
//            _logger.LogInformation("DEBUG: ResearchDepth count = {Count}", request.ResearchDepth?.Count ?? 0);

//            using var httpRequest = new HttpRequestMessage(HttpMethod.Post, requestUrl);

//            if (!string.IsNullOrWhiteSpace(_mlApiKey))
//                httpRequest.Headers.Add("X-API-Key", _mlApiKey);

//            // ✅ Build JSON - مع null checks
//            var geographyString = request.TargetGeography != null && request.TargetGeography.Any()
//                ? string.Join(",", request.TargetGeography)
//                : "Global";

//            var depthString = request.ResearchDepth != null && request.ResearchDepth.Any()
//                ? string.Join(",", request.ResearchDepth)
//                : "standard";

//            _logger.LogInformation("DEBUG: geography string = '{Value}'", geographyString);
//            _logger.LogInformation("DEBUG: depth string = '{Value}'", depthString);

//            var jsonRequest = new
//            {
//                therapeutic_area = request.TherapeuticArea ?? "",
//                specific_product = request.SpecificProduct,
//                indication = request.Indication,
//                target_geography = geographyString,
//                research_depth = depthString,
//                files = request.Files != null && request.Files.Any()
//                ? request.Files.Select(f => new
//                {
//                    file_id = f.FileId,
//                    file_name = f.FileName,
//                    file_url = f.FileUrl,
//                    file_size = f.FileSize,
//                    file_extension = f.FileExtension
//                }).ToArray()
//                : Array.Empty<object>()
//            };

//            var jsonContent = JsonConvert.SerializeObject(jsonRequest, Formatting.Indented);

//            _logger.LogInformation("========================================");
//            _logger.LogInformation("FULL REQUEST JSON:");
//            _logger.LogInformation(jsonContent);
//            _logger.LogInformation("========================================");

//            httpRequest.Content = new StringContent(
//                jsonContent,
//                System.Text.Encoding.UTF8,
//                "application/json");

//            // ✅ Log headers
//            _logger.LogInformation("Content-Type: {ContentType}", httpRequest.Content.Headers.ContentType);
//            _logger.LogInformation("Content Length: {Length}", jsonContent.Length);

//            var response = await _httpClient.SendAsync(httpRequest, cancellationToken);
//            var responseContent = await response.Content.ReadAsStringAsync(cancellationToken);

//            _logger.LogInformation("ML API Status: {Status}", response.StatusCode);
//            _logger.LogInformation("Response Length: {Length}", responseContent.Length);

//            if (!response.IsSuccessStatusCode)
//            {
//                _logger.LogError("========================================");
//                _logger.LogError("ML API ERROR RESPONSE:");
//                _logger.LogError(responseContent);
//                _logger.LogError("========================================");
//                throw new Exception($"ML API Error ({response.StatusCode}): {responseContent}");
//            }

//            var result = JsonConvert.DeserializeObject<GenerateMarketAnalysisResponse>(responseContent);

//            if (result == null)
//                throw new JsonException("Null response from ML API");

//            _logger.LogInformation("✓ Success! ID: {Id}", result.Id);

//            return result;
//        }
//        catch (Exception ex)
//        {
//            _logger.LogError(ex, "ML API call failed");
//            throw;
//        }
//    }
//    public async Task<bool> HealthCheckAsync()
//    {
//        try
//        {
//            var response = await _httpClient.GetAsync($"{_mlApiBaseUrl}/health");
//            return response.IsSuccessStatusCode;
//        }
//        catch
//        {
//            return false;
//        }
//    }
//}

//#endregion 
#endregion



#region MLApiService

using ApplicationLayer.Contracts.DTOs;
using ApplicationLayer.Interfaces.Services;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Net.Http.Headers;

namespace InfrastructureLayer.Services;

public class MLApiService : IMLApiService
{
    private readonly HttpClient _httpClient;
    private readonly ILogger<MLApiService> _logger;
    private readonly string _mlApiBaseUrl;
    private readonly string? _mlApiKey;

    public MLApiService(
        HttpClient httpClient,
        IConfiguration configuration,
        ILogger<MLApiService> logger)
    {
        _httpClient = httpClient;
        _logger = logger;

        _mlApiBaseUrl = configuration["MLApi:BaseUrl"]
            ?? throw new InvalidOperationException("MLApi:BaseUrl not configured");

        _mlApiKey = configuration["MLApi:ApiKey"];

        if (int.TryParse(configuration["MLApi:TimeoutSeconds"], out int timeout))
            _httpClient.Timeout = TimeSpan.FromSeconds(timeout);
    }

    public async Task<GenerateMarketAnalysisResponse> GenerateAnalysisAsync(
        MLApiRequestDto request,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var requestUrl = $"{_mlApiBaseUrl}/api/v1/report";

            _logger.LogInformation("========================================");
            _logger.LogInformation("Calling ML API: {Url}", requestUrl);

            using var form = new MultipartFormDataContent();

            // Required fields
            form.Add(new StringContent(request.TherapeuticArea ?? ""), "therapeutic_area");

            if (!string.IsNullOrEmpty(request.SpecificProduct))
                form.Add(new StringContent(request.SpecificProduct), "specific_product");

            if (!string.IsNullOrEmpty(request.Indication))
                form.Add(new StringContent(request.Indication), "indication");

            // Lists
            foreach (var geo in request.TargetGeography ?? new List<string>())
            {
                form.Add(new StringContent(geo), "target_geography");
            }

            foreach (var depth in request.ResearchDepth ?? new List<string>())
            {
                form.Add(new StringContent(depth), "research_depth");
            }

            // Files
            foreach (var file in request.Files ?? new List<MLApiFileDto>())
            {
                _logger.LogInformation("Downloading file from: {Url}", file.FileUrl);

                var fileResponse = await _httpClient.GetAsync(file.FileUrl);

                if (!fileResponse.IsSuccessStatusCode)
                {
                    _logger.LogError("File not accessible: {Url}", file.FileUrl);
                    continue;
                }

                var stream = await fileResponse.Content.ReadAsStreamAsync();

                var fileContent = new StreamContent(stream);
                fileContent.Headers.ContentType =
                    new MediaTypeHeaderValue("application/pdf");

                form.Add(fileContent, "files", file.FileName);
            }

            if (!string.IsNullOrWhiteSpace(_mlApiKey))
                _httpClient.DefaultRequestHeaders.Add("X-API-Key", _mlApiKey);

            var response = await _httpClient.PostAsync(requestUrl, form, cancellationToken);

            var responseContent = await response.Content.ReadAsStringAsync(cancellationToken);

            _logger.LogInformation("ML API Status: {Status}", response.StatusCode);

            if (!response.IsSuccessStatusCode)
            {
                _logger.LogError("ML API ERROR RESPONSE:");
                _logger.LogError(responseContent);

                throw new Exception($"ML API Error ({response.StatusCode}): {responseContent}");
            }

            var result = Newtonsoft.Json.JsonConvert
                .DeserializeObject<GenerateMarketAnalysisResponse>(responseContent);

            if (result == null)
                throw new Exception("Invalid response from ML API");

            _logger.LogInformation("✓ ML Analysis generated successfully. ID: {Id}", result.Id);

            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "ML API call failed");
            throw;
        }
    }

    public async Task<bool> HealthCheckAsync()
    {
        try
        {
            var response = await _httpClient.GetAsync($"{_mlApiBaseUrl}/health");
            return response.IsSuccessStatusCode;
        }
        catch
        {
            return false;
        }
    }
}

#endregion